# Generated by Django 2.1.7 on 2019-04-16 20:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpage',
            old_name='body',
            new_name='first_indicator_body',
        ),
        migrations.RenameField(
            model_name='reportpage',
            old_name='intro',
            new_name='first_indicator_caption',
        ),
        migrations.RemoveField(
            model_name='reportpage',
            name='header_image',
        ),
        migrations.AddField(
            model_name='reportpage',
            name='first_indicator_number',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportpage',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='second_indicator_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='second_indicator_caption',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportpage',
            name='second_indicator_number',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
