# Generated by Django 2.1.7 on 2019-04-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('reports', '0002_auto_20190416_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpage',
            old_name='report_file',
            new_name='full_report_document',
        ),
        migrations.AddField(
            model_name='reportpage',
            name='summary_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
