# Generated by Django 2.1.7 on 2019-04-17 07:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190417_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpage',
            old_name='first_indicator_caption',
            new_name='indicator_caption',
        ),
        migrations.RenameField(
            model_name='reportpage',
            old_name='first_indicator_number',
            new_name='indicator_number',
        ),
        migrations.RemoveField(
            model_name='reportpage',
            name='first_indicator_body',
        ),
        migrations.RemoveField(
            model_name='reportpage',
            name='second_indicator_body',
        ),
        migrations.RemoveField(
            model_name='reportpage',
            name='second_indicator_caption',
        ),
        migrations.RemoveField(
            model_name='reportpage',
            name='second_indicator_number',
        ),
        migrations.AddField(
            model_name='reportpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
