# Generated by Django 2.1.7 on 2019-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='resourceindexpage',
            name='sub_headline',
        ),
        migrations.RemoveField(
            model_name='resourceindexpage',
            name='video_header',
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='external_link',
            field=models.URLField(blank=True),
        ),
    ]
