# Generated by Django 2.1.7 on 2019-07-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190723_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcepage',
            name='video_header',
        ),
    ]
