# Generated by Django 2.1.7 on 2019-07-23 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resourcepage_video_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceindexpage',
            name='sub_headline',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
