# Generated by Django 2.1.7 on 2019-07-23 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourceindexpage_sub_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
