# Generated by Django 2.1.7 on 2019-07-23 06:05

from django.db import migrations
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resourcepage_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceindexpage',
            name='sub_headline',
        ),
        migrations.AddField(
            model_name='resourceindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
