# Generated by Django 2.1.7 on 2019-07-23 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20190723_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='sub_headline',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
