# Generated by Django 2.1.7 on 2019-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resourcepage_sub_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
