# Generated by Django 2.1.7 on 2019-09-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20190819_1459'),
        ('resources', '0008_auto_20190828_1151'),
    ]

    operations = [
    ]
