# Generated by Django 2.1.7 on 2019-10-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20190828_1151'),
        ('resources', '0008_auto_20190819_1459'),
    ]

    operations = [
    ]
