# Generated by Django 2.1.7 on 2019-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='website',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='category',
            field=models.ManyToManyField(to='partners.PartnerCategories'),
        ),
    ]
