# Generated by Django 2.1.7 on 2019-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=models.CharField(default='Headline', max_length=250),
            preserve_default=False,
        ),
    ]
