# Generated by Django 2.1.7 on 2019-04-17 05:59

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190417_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.CharField(max_length=250)),
                ('questions', models.CharField(max_length=250)),
                ('contact', wagtail.core.fields.RichTextField(blank=True)),
            ],
        ),
    ]
