# Generated by Django 2.1.7 on 2019-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tooltip_1',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='tooltip_2',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='tooltip_3',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
