# Generated by Django 2.1.7 on 2019-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='sub_headline',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='video_header',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
